[mypy]
plugins = mypy_django_plugin.main
ignore_missing_imports = True
disallow_untyped_defs = True
strict_optional = True
warn_unused_ignores = True
check_untyped_defs = True
warn_return_any = True

[mypy.plugins.django-stubs]
django_settings_module = TwitterUnfollow.settings
